ContactsTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: ContactsTable-${opt:stage}
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions:
      - AttributeName: collegeName
        AttributeType: S
    KeySchema:
      - AttributeName: collegeName
        KeyType: HASH
